### ISSUE TITLE
Create models for ALM APIs

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#215]
## Category

- [x] Feature request

## Describe the feature

- Add the ability to call the ALM APIs as descirbed in the article: [https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest)
- Unit Tests for calling the APIs
- If there are special requirements or permissions with this model, add to the documentation

## Contributing

We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: [https://pnp.github.io/pnpcore/articles/contributor/readme.html](https://pnp.github.io/pnpcore/articles/contributor/readme.html)

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

**Comment by s-KaiNet** [comment]
I would like to deep dive into this awesome library internals and implement this issue if there are no objections.

**Comment by s-KaiNet** [comment]
@jansenbe I have a question regarding the API itself. I will really appreciate it if you or other team members, who are deeply involved in the library development, are able to provide their input.   

In the official [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest), we have only a few methods available for the TenantAppCatalog endpoint (Add, SyncSolutionToTeams). However, when looking at the [metadata](https://s-kainet.github.io/sp-rest-explorer/#/_api/web/TenantAppCatalog) it appears that currently there are some more methods.   

Another story is that there is also a site collection app catalog [endpoint](https://s-kainet.github.io/sp-rest-explorer/#/_api/web/SiteCollectionAppCatalog). Here we have a lot fewer methods than in the TenantAppCatalog.   

- should we implement additional methods currently available in the metadata for the TenantAppCatalog endpoint?
- if the answer above is yes, then what would be the best approach to distinguish TenantAppCatalog and SiteCollectionAppCatalog calls? Because some methods will be available only for tenant catalog (`DownloadTeamsSolution`, `SolutionContainsTeamsComponent`..., some others) and it might not be clear for a developer, that you can call them only for tenant app catalog. 
  One option would be just document it in the method signature and that's it. 
  Another option would be using two different managers (with common codebase) - `GetTenantAppManager()` (with all the methods from [metadata](https://s-kainet.github.io/sp-rest-explorer/#/_api/web/TenantAppCatalog) for TenantAppCatalog) and `GetSiteCollectionAppManager()` for SiteCollectionCatalog. In that case it will be very clear for a developer which catalog they work with. 
  Alternateveliy, we can still use one `AppManager` class, however in that case we should use `AppCatalogScope` enum for some methods. Also, when we use one `AppManager` it's not very clear what to do when a developer tries to call a method from tenant app catalog using site collection context (silently switch context? throw an exception?).
