### ISSUE TITLE
Document the similarities/differences between CSOM and PnP Core SDK

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#300]
## Category

- [x] Feature request

## Describe the feature

PnP Core SDK feels a bit like CSOM but works not always the same...clarify the differences in documentation to assist folks moving over from CSOM.

**Comment by jansenbe** [comment]
Waiting for the refactoring @PaoloPia is working on as this will further align the behavior between Core SDK and CSOM

**Comment by olemp** [comment]
@jansenbe Is it possible now or will it be possible at any time to get the underlying client context (for CSOM)? I'm looking for the GetChanges API on the lists, and it seems to be "missing" so far.

**Comment by s-KaiNet** [comment]
@jansenbe do you have any samples or plan how these docs should be structured? Otherwise, I can try to create the initial page with the similarities/differences between CSOM and PnP Core SDK. I don't think I will cover all possible scenarios, but maybe at least it will be a starting point. Better to have something to start with, than nothing :)

**Comment by jansenbe** [comment]
Hi @s-KaiNet , I don't have any specific structure in mind...you do know both models very well, so I've no doubt your "starting point" already will be very good. I'll assign this one to you then. Thanks!!

**Comment by jansenbe** [comment]
Thx @s-KaiNet 🚀🥇
