### ISSUE TITLE
Field/ContentType will need to work in different context (site/list)

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#55]
## Category

- [x] Feature request

## Describe the feature

Decorating is done with a specific context in mind (e.g. Site) when the same object can also be used within a different context (e.g. List). Think about a mechanism to handle this

**Comment by ypcode** [comment]
Hi @PaoloPia @jansenbe,

Just an idea here, since I have been thinking a bit about it.
Don't you think an easy way to achieve that would be to add multiple [SharePointType] attribute to the 'child' model class with a new metadata (e.g. `ParentScope`)
Something similar to :
```
[SharePointType("SP.Web"]
public class Web { }
[SharePointType("SP.List"]
public class List {}

[SharePointType("SP.ContentType", ParentScope="SP.Web", Url="/web/contenttypes")]
[SharePointType("SP.ContentType", ParentScope="SP.List", Url="/web/lists(guid'')/contenttypes")]
public class ContentType {}
```

I am not sure it is doable in practice, but I feel it an elegant and "confortable" way to address this purpose ?

What do you think ?

**Comment by jansenbe** [comment]
That was exactly the plan I started coding on today :-)

**Comment by ypcode** [comment]
Awesome ! I like when we ending thinking the same :D

**Comment by jansenbe** [comment]
Implemented
