### ISSUE TITLE
Calling Sharepoint Social Data using PNP Core SDk

### ISSUE THREAD

**Issue by somdeepgniyogi** [pnp/pnpcore#624]
I am trying read user profile using PNP core SDK however I am not able to achieve the same. 

Please help me as I am not able to reference the PeopleManager class

BR

**Comment by jansenbe** [comment]
Hi @somdeepgniyogi , can you provide more details about the scenario you want to realize using PeopleManager? Today we've not yet wrapped the PeopleManager.


Research links:
- https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/dn790354(v=office.15)?redirectedfrom=MSDN
- https://www.sharepointpals.com/post/user-profile-properties-with-rest-api-sharepoint-office-365/
- https://piyushksingh.com/2021/03/29/sharepoint-online-get-user-profile-properties/

**Comment by somdeepgniyogi** [comment]
Dear Jansenbe,

I am trying to use PNP core sdk from an application hosted in Azure. The application is in .net core and I refencing PNP core sdk using downstreamapi.

My requirement is to read user profile data using SharePoint Online Social API’s.

I could do this using JavaScript PNP libraries however I want to utilize PNP Core SDK C# libraries to do the same.

Can you kindly help me out how to do that?

BR,
Somdeep

**Comment by jansenbe** [comment]
Thanks for the clarification @somdeepgniyogi .

As mentioned today we don't have built in support, I'll add that to our todo list. Depending on how much you're using `PeopleManager` you can opt to use our "call custom API" feature (https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request) and make the requests yourself. Below are two `PeopleManager` samples. The response variable contains a property named `Response` holding the JSON content of the API call.

```csharp
// Get 2 properties for the current user
var apiRequest = new ApiRequest(ApiRequestType.SPORest, "_api/sp.userprofiles.peoplemanager/GetMyProperties?$select=PictureUrl,AccountName");
var response = context.Web.ExecuteRequest(apiRequest);

// Get all properties for the named user
apiRequest = new ApiRequest(ApiRequestType.SPORest, "_api/sp.userprofiles.peoplemanager/GetPropertiesFor(accountName='i:0%23.f|membership|kevinc@bertonline.onmicrosoft.com')");
response = context.Web.ExecuteRequest(apiRequest);
```

Once we have this API wrapped in PnP Core SDK you can use that, but in the meantime using the manual approach can hopefully unblock you.

**Comment by somdeepgniyogi** [comment]
Dear @jansenbe ,

Thanks a lot for your support.

I was using the same approach but wanted to enquire if you already have any supporting libraries.

Thanks again

Best Regards

**Comment by s-KaiNet** [comment]
I would like to work on this. People manager indeed a nice thing to have, but we still miss it in the library. @jansenbe please assign to me.

**Comment by s-KaiNet** [comment]
@jansenbe @somdeepgniyogi   

The official docs page [here](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/dn790354(v=office.15)) says that you should use [Following people and content REST API](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/following-people-and-content-rest-api-reference-for-sharepoint?redirectedfrom=MSDN#resource-endpoints-for-following-people-and-following-content-tasks) for almost all  _follow*_ methods. The API endpoint for following is `_api/social.following`. This API has more options when following the content, that's why it's recommended to use it instead of `_api/sp.userprofiles.peoplemanager`. Still `_api/sp.userprofiles.peoplemanager` has some useful methods like getting user properties and others. It means that we need both `_api/sp.userprofiles.peoplemanager` and  `_api/social.following`.

Here we have a few options on how to implement it in PnP SDK. 
1. We can put everything under the new `PnPContext` property, say `UserProfile`. In this case the library consumer will use `context.UserProfile.GetMyProperties()`, `context.UserProfile.Follow()`, `context.UserProfile.GetFollowersFor()`, etc. One entry for following and userprofiles.
2. Alternatively, we can use two different entities on `PnPContext`, for example `UserProfile` and `Following`. Every entity implements related APIs for user profiles and following content. In this case for a consumer it will be: `context.UserProfile.GetMyProperties()`, `context.Following.Follow()`, `context.Following.GetFollowersFor()`, etc. Two different entries - one for userprofiles and one for following - semantic separation. 
3. And finally the last option is a kind of improvement over the second one - create a new property `Social` under `PnPContext` and use two different entities for different APIs. Meaning -  `context.Social.UserProfile.GetMyProperties()`, `context.Social.Following.Follow()`, `context.Social.Following.GetFollowersFor()`, etc. 

Just looking for your advice on what would be the best option (maybe your option `#4`). Personally, I like option `#3` because in this case, we have cleaner semantic separation. We don't "pollute" `PnPContext` with additional properties (if we need another social API in the future, we can add it to the `Social`, root `PnPContext context` is cleaner).

**Comment by jansenbe** [comment]
@s-KaiNet : I'm in favor of option 3.
