### ISSUE TITLE
Check is website already exist?

### ISSUE THREAD

**Issue by indieza** [pnp/pnpcore#629]
## Category

- [x] Question

Hello,
Is there some way to check is website already exist in a target tenant. In SharePointPnPCoreOnline we have this.clientContext.Site.RootWeb.WebExists(URL), but in the PnP.Core SDK I cannot find relevant solution over the issue.

Regards,
Simeon Valev

**Comment by jansenbe** [comment]
@indieza : a simple and recommended solution would be to wrap the context creation in a try catch as creating a PnPContext will make a REST call to the site...so that will throw an exception if the URL is wrong. Alternative approach is using our in-preview admin component and getting the site properties (https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-sites.html#getting-and-setting-site-collection-properties). This however does require admin permissions.

The mentioned `WebExists` method only works for sub sites, there's a `WebExistsFullUrl` method in SharePointPnPCoreOnline  which is also based upon catching the error when trying to create a context.

**Comment by indieza** [comment]
Thanks for the quick response. It works for me. I will close the issue.

Regards,
Simeon Valev
