### ISSUE TITLE
Extend the domain model for User Custom Actions

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#63]
## Category

- [x] Feature request

## Describe the feature

The domain model needs to be extended to support user custom actions. These live at site/web and list level. See https://aka.ms/pnp/coresdk/contributors on how to get started.

This is a nice work item for new contributors, if you're interested in it please reply on this list item and we'll help you get started.

**Comment by jansenbe** [comment]
I'll start working on this one

**Comment by jansenbe** [comment]
Removed myself for the time being so that others can pick this up

**Comment by jansenbe** [comment]
Moving to beta 1 milestone

**Comment by ypcode** [comment]
I'll take this one

**Comment by ypcode** [comment]
The User Custom Actions are working for all "modern" custom action (SPFx extensions) and I did a test of setting a "classic" custom action by disabling no script with PnP PowerShell and it did work.
However since the DenyCustomizePage property doesn't seem to be available through SP REST and can then not easily be implemented, I left the classic custom action test commented out for now (even if I know it works well).

@jansenbe I'll let you decide whether or not you want to close this issue :)

**Comment by jansenbe** [comment]
Turning off noscript on modern sites is not something we should promote. This issue can be closed now. Thanks again for this great work @ypcode !
