### ISSUE TITLE
Simplify to set user field value when add a list item

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#915]
To handle user values for a list item. Can't this be simplified?
https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#user-fields

Support to crate an instance of FieldUserValue, it's now protected.

FieldUserValue userValue = new FieldUserValue();
userValue.LookupId = user.Id;  // user => ensuredUser

values.Add("MyUserField", userValue);

var addedItem = await myList.Items.AddAsync(values);

**Comment by jansenbe** [comment]
@matsla : originally we needed the IField reference when processing list items, but after a refactoring a while ago this seems to be  not relevant anymore (at least after a quick code check)...so, I think we can simplify the model a bit here. Will do some more checking / prototyping and will, if all turns out fine, update our code.

**Comment by jansenbe** [comment]
@matsla : the simplified model has been implemented, from now on you can directly instantiate the needed `FieldXXXValue` and `FieldValueCollection` classes without requiring a reference to the used `IField`. See https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#url-fields for the updates docs.

**Comment by trueleader** [comment]
@jansenbe Any idea when this will be released?

**Comment by jansenbe** [comment]
We are actually planning a release soon, probably next week already
